import Head from "next/head";

import { Inter } from "@next/font/google";

import CardComponent from "./components/card";
import HeaderComponent from "./components/header";
import SearchComponent from "./components/search";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeaderComponent />
      <SearchComponent />
      <CardComponent
        imageSrc={""}
        title={""}
        description={""}
        link={""}
        statues={""}
        createdAt={""}
      />
    </>
  );
}
